name: First workflow
on:
  push:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2 
  
      - name: Check terraform
        run: |
          whereis terraform

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Check terraform again
        run: |
          whereis terraform

      - name: Print Hello World
        run: |
          echo "Hello World!"
