name: First workflow
on:
  push:

env:
  AWS_SECRET_ACCESS_KEY: VALUE1

jobs:
  hello-world:
    name: Hello World
    env:
      AWS_SECRET_ACCESS_KEY: VALUE2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2 

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform init
        run: |
          terraform init
          echo $AWS_SECRET_ACCESS_KEY

      - name: Terraform plan
        env:
          AWS_SECRET_ACCESS_KEY: VALUE3
        run: |
          echo "terraform plan"

      - run: |
            echo $AWS_SECRET_ACCESS_KEY

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - run: |
          echo $AWS_SECRET_ACCESS_KEY