name: First workflow
on:
  push:

env:
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  terraform:
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2 

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform init
        run: |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan