# name: 
on:
  push:

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - run: |
          echo "Hello World!"
